jst-seminar-rostlab-tum/wfp-hunger-map

src/components/Chatbot/Chatbot.tsx, src/services/api/chatbot.ts, src/types/chatbot.ts
- services/api/chatbot.ts: implemented the basic logic for back-end communication
- types/chatbot.ts: changed IMessage interface so that the format is according to openai api
- components/Chatbot/Chatbot.tsx: adjusted send message with response, message history is also included
IMPORTANT: the implementation needs also some adjustments on the back-end side. (I will make a pull request for those changes in a couple of minutes)
=> feat: implement communication with back-end for the chatbot

tailwind.config.js
sorry guys, if tailwind wasn't working for you, this was the reason...
=> fix: use correct paths in tailwind config

src/components/PopupModal/PopupModal.tsx
small changes regarding padding and text size of popup modal espcially in mobile version, to save more space
=> fix: change padding and text size of popup modal

package.json, src/app/providers.tsx, src/components/AlertsMenu/AlertButton.tsx, src/components/AlertsMenu/AlertsMenu.tsx, src/components/Map/Alerts/ConflictLayer.tsx, src/components/Map/Alerts/HazardLayer.tsx, src/domain/hooks/alertHooks.ts, src/domain/props/AlertButtonProps.tsx, yarn.lock
When the alerts are loading, a loading spinner is shown on the button.
Also added tanstack devtools with this PR, it comes handy sometimes.
=> Alert loading state

src/components/Accordions/Accordion.tsx
->  i disable the scrollbar thing by hidding the overflow. Now hopefully, the scrollbar problem should be fixed
=> fix: disable scrollbar when accordion got expanded

src/components/HungerAlert/HungerAlert.tsx
i'm not quite sure about the text of tooltip. I like the text, but please feel free to give suggestions
=> feat: add tooltip to hunger alert

next.config.js, package.json, src/app/elements/page.tsx, src/styles/globals.css, svg.d.ts, tsconfig.json, yarn.lock
so what i did was first convert .svg into react component using svgr webpack [Link svgr Webpack](https://react-svgr.com/docs/webpack/). This webpack helps svg to convert into react component. The colors for svg are define in global.css. Beforehand, i already talked with samuel, whether i can touch next.config.js or not. 
In order to test this, i'm already calling into elements/page.tsx. localhost:3000/elements, you can test the svg color thing.
=> feat: implement change of color of svg for light/dark modes

src/app/about/page.tsx, src/app/data_sources/page.tsx, src/components/Accordions/Accordion.tsx, src/components/Legend/LegendContainer.tsx, src/domain/props/AccordionProps.tsx
now multiple accordions can expanded at once in LegendContainer, About and DataSources
=> feat: allow multiple accordions to expand at once

src/app/elements/page.tsx, src/components/Search/SearchBar.tsx, src/components/Sidebar/Sidebar.tsx, src/domain/props/SearchBarProps.ts
I added a generic search bar component and put it in our side bar.
=> feat: search bar

src/components/Map/NutritionChoropleth.tsx, src/operations/map/NutritionChoroplethOperations.ts
now alerts are only disable when the country is clicked in nutrition view. beforehand alerts were disable also in global view
=> fix: fix alert appearance in nutrition view

tailwind.config.js
Change the color of "not analyzed data" in nutrition legend
=> fix: fix color of not analyzed data in nutrition view

src/components/Accordions/AccordionBoxItems.tsx, src/components/Accordions/AccordionContainer.tsx, src/components/Map/FcsAccordion.tsx, src/components/Map/IpcMap/IpcAccordion.tsx, src/components/Map/NutritionAccordion.tsx, src/components/Table/CustomTable.tsx, src/domain/props/AccordionContainerProps.tsx
https://linear.app/world-food-programme-wfp/issue/F-136/accordion-should-take-the-width-of-the-parent-element
=> feat: AccordionContainer max width

src/components/Accordions/AccordionBoxItems.tsx
- fix: when changing alert opening the legend accordion was not working properly
=> fix: legend accordions not opening properly

src/components/Map/CountryLoading.tsx, src/components/Map/FcsChoropleth.tsx, src/components/Map/IpcMap/IpcChoropleth.tsx, src/components/Map/NutritionChoropleth.tsx, src/domain/props/CountryLoadingProps.tsx, tailwind.config.js
Add pulse animation to the country view in nutrition, fcs and ipc.
=> feat: add loading pulse effect on country view

next.config.js
source: https://stackoverflow.com/a/79229889/10719279
=> Disable cache max size

src/components/Map/Map.tsx
- send event when the selected country changes (it takes some time (~one day) for these event to reach GA)
- created explorations that show only our custom events
You can see them here: https://analytics.google.com/analytics/web/?authuser=3#/analysis/p468690329
Sign in with the jstwfp@gmail.com account (pwd in notion)
=> Google Analytics improvements

src/app/about/layout.tsx, src/app/comparison-portal/layout.tsx, src/app/data_sources/layout.tsx, src/app/disclaimer/layout.tsx, src/app/download-portal/layout.tsx, src/app/error.tsx, src/app/not-found.tsx, src/app/wiki/layout.tsx, src/components/Accordions/AccordionBoxItems.tsx, src/components/Legend/PointLegend.tsx, src/components/Map/Alerts/CountryAlerts/CountryAlertLegendItem.tsx, src/components/Topbar/Topbar.tsx, src/domain/constant/legend/mapLegendData.tsx
**Initial Problem:** In some (independent) cases, the Data Source page was shown in a corrupted way and without interactivity. A reload didn't fix it. [Screenshot](https://uploads.linear.app/620c9493-591e-4baa-8cb8-dabda150c013/ad2ab5d9-b998-47fb-86c4-514c0f3bdbf8/c8a9b20f-5e1f-4f32-9824-2ed43025fdab)
**Repro:** I couldn't reproduce the issue except for one time where I had collected no details. However, the screenshot looks similar to the initial response from the server (i.e. the server-rendered initial portion of the page): [Screenshot from Devtools](https://github.com/user-attachments/assets/d105f374-f57f-4fb9-b9fc-9138220f273c)
**Fix attempt:** It seems like something went wrong right after the browser received the initial response. At this point, React hydration takes place, so I …
=> Feature/f-169 Fix Hydration Errors

src/components/Tooltip/Tooltip.tsx
closes: https://linear.app/world-food-programme-wfp/issue/F-236/tooltip-code-docs
=> F-236 Tooltip code docs

src/components/Sidebar/CollapsedSidebar.tsx, src/components/Tooltip/Tooltip.tsx, src/domain/props/TooltipProps.tsx
-> I changed the position of the tooltip, instead of the top i placed tooltip to the right side.
If the tooltip placement was on tooltip, then it's look like this 
https://github.com/user-attachments/assets/3e109f04-d124-4ad2-8be6-44782b0a1cfd
=> feat: add tooltip to the collapsed sidebar

src/components/Charts/helpers/ChartContainer.tsx, src/components/ComparisonPortal/NoDataHint.tsx
closes: https://linear.app/world-food-programme-wfp/issue/F-222/dont-display-no-data-for-xxx-if-there-is-no-data-for-all-countries
=> F-222: Don't display "no data for xxx" if there is no data for all countries

src/components/Map/FcsMap/FcsChoropleth.tsx, src/components/Map/FcsMap/FcsCountryChoropleth.tsx, src/components/Map/Map.tsx, src/components/Map/NutritionMap/NutritionChoropleth.tsx, src/components/Map/NutritionMap/NutritionStateChoropleth.tsx, src/components/Sidebar/CollapsedSidebar.tsx, src/domain/props/FcsChoroplethProps.ts, src/domain/props/FcsCountryChoroplethProps.ts, src/domain/props/NutritionChoroplethProps.tsx, src/domain/props/NutritionStateProps.ts
zooming in for the second time to a country is a bit weird, the labels show up before the zoom finishes, should I do something about that?
=> fix: rerun hook if selectedCountry changes

src/components/Accordions/AccordionBoxItems.tsx
- added key to accordion component
=> fix: when switching between alerts or map modes accordions dont work properly

src/components/Topbar/Topbar.tsx
Please check if the space between chatbot button and theme switch looks good to you
=> feat: added right margin to theme switch

src/components/Analytics/CookieConsentPopup.tsx, src/styles/globals.css, tailwind.config.js
want to test accessibility, that's why need to open draft PR
=> feat: change color of the button to check accessibility

src/components/Map/FcsMap/FcsAccordion.tsx
Now user can scroll the accordions without going to the scrollbar
=> feat: add scroll behavior without using scrollbar

src/operations/map/MapOperations.tsx
Add inline docs for new tooltip functionality
=> Inline docs for new tooltip method

src/components/InfoPopover/InfoPopover.tsx, src/components/Map/IpcMap/IpcCountryChoropleth.tsx
and a small refactor while I'm there
=> fix ipc regions

.all-contributorsrc, .env_template, Dockerfile, README.md, next.config.js, package.json, src/app/page.tsx, src/infrastructure/repositories/GlobalDataRepositoryImpl.ts, yarn.lock
sadly the CLI doesn't work and I didn't see the point of using the bot, so just edit the all-contributorsrc file directly and run `yarn all-contributors generate` if you need to edit smth.
f-267 and f-273
=>  add contributors section to readme & more

src/operations/charts/CategoricalChartOperations.ts
closes: https://linear.app/world-food-programme-wfp/issue/F-264/charts-inconsistent-color-palette-for-many-countries
=> fix: categorical chart bars different colors

src/components/Chatbot/Chatbot.tsx, src/domain/contexts/ChatbotContext.tsx, src/domain/entities/chatbot/BackendCommunication.ts, src/domain/entities/chatbot/Chatbot.ts, src/infrastructure/repositories/ChatbotRepositoryImpl.ts, src/operations/download-portal/DownloadPortalOperations.tsx
This PR is the complementary part of the [feat/f-233-years-in-review-pdf-chatting](https://github.com/jst-seminar-rostlab-tum/wpf-chatbot-backend/tree/feat/f-233-years-in-review-pdf-chatting) branch on the BE side.
It adjusts the interface for supporting Year in Review reports chatting.
=> feat: adjust BE interface for year_in_review reports

src/components/Chatbot/Chatbot.tsx
This pull request includes several changes to the `HungerMapChatbot` component in `src/components/Chatbot/Chatbot.tsx`. The changes primarily focus on adjusting the layout and styling of various elements within the chatbot interface.
Styling adjustments:
* Updated the `CardBody` component to have a height of `4/5` to better fit the content.
* Increased the bottom margin of the default prompt buttons for better spacing.
* Reduced the padding of the `CardFooter` component to `p-2` for a more compact layout.
* Limited the maximum height of the `textarea` to `20` to prevent it from growing too large. @Tschonti  I think it will help to limit the text input area to avoid to long text occupy the chatbot interface.
=> f-251/Chatbot-UI-finanlization

src/app/comparison-portal/loading.tsx, src/components/ComparisonPortal/ComparisonPortalSkeleton.tsx, src/components/ComparisonPortal/RegionSelection.tsx, src/components/ComparisonPortal/RegionSelectionSkeleton.tsx
fix selection skeleton on region tab
=> fix: selection skeleton

src/components/Subscribe/NestedPopover.tsx, src/components/Subscribe/Subscribe.tsx, src/domain/entities/subscribe/Subscribe.ts
Country selection on subscribe was broken
=> fix: country selection

src/components/Map/FcsMap/FcsAccordion.tsx, src/operations/map/FcsFoodSecurityOperations.tsx
the fcs and rcsi scores will show a slight upward trend for the next 90 days :D
=> mock prediction data

src/components/Charts/CategoricalChart.tsx, src/operations/charts/CategoricalChartOperations.ts, src/operations/charts/ChartColorsOperations.ts, src/operations/charts/ContinuousChartOperations.ts
fix: removed animations fro all charts
fix for comparison portal: colors for different countries/states stay the same over multiple graphs
---
=> fix: use same colors for same countries
